Simulation = "DecentralizedCellCNN"
Servers = 3
Bf = 2
Suite = "Ed25519"
Rounds = 1
RunWait = "24h"
Bandwidth = 1000
Mininet = false
KFold = 2
Time = true

Hosts, NbrEpochs, NbrLocalIter, NodeBatchSize
1, 100, 1, 50