Simulation = "CellCNN"
Servers = 12
Bf = 2
Suite = "Ed25519"
Rounds = 1
RunWait = "24h"
Bandwidth = 1000
Debug = false
TrainEncrypted = true
Deterministic = false
Fake = true
Path = "../../normalized/"
PathCryptoFiles = "secrets/"

Hosts, Epochs, PartyDataSize, Samples, Cells, Features, Filters, Classes, MaxIterations, NodeBatchSize
3, 1, 500, 1500, 200, 38, 8, 2, 5, 100